import type { NextPage } from "next";
import Head from "next/head";
import { SyntheticEvent, useState } from "react";
import IconButton from "../components/IconButton";
import Skill from "../components/Skill";
import { Skills } from "../Data/Skills";
import { TiDelete } from "react-icons/ti";

const Home: NextPage = () => {
  const [skills, setSkills] = useState<string[]>([]);
  const [skillValue, setSkillValue] = useState<string>("");
  const [suggestedSkill, setSuggestedSkill] = useState(Skills);

  // add skill
  const addSkill = (skill: string) => {
    setSkills((prevSkills) => [...prevSkills, skill]);
  };

  const deleteInputedSkill = (id: number) => {
    const other = skills.filter((_, skillId) => skillId !== id);
    setSkills(other);
  };

  // remove skill
  const removeSkill = () => {
    const remainSkills = skills.slice(0, -1);
    setSkills(remainSkills);
  };

  const removeSuggestedSkill = (skill: string) => {
    // add this skill
    addSkill(skill);

    // remove it
    const othersSuggestedSkill = suggestedSkill.filter(
      ({ skillName }) => skillName !== skill
    );
    setSuggestedSkill(othersSuggestedSkill);
  };

  // form submit handler
  const handleOnSubmit = (e: SyntheticEvent) => {
    e.preventDefault();
    if (skillValue) {
      addSkill(skillValue);
    }
    setSkillValue("");
  };

  const BackSpaceHandler = () => {
    console.log("back space key pressed");
  };

  return (
    <>
      <Head>
        <title>Next Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="text-3xl text-green-600 text-center mt-5">
        List Down your skills!
      </h2>
      <div className="shadow-md bg-green-50 rounded-md w-[95%] max-w-2xl mx-auto mt-5 p-6">
        <div className={`flex items-center flex-wrap gap-2 mb-4`}>
          {skills.map((skillName, i) => (
            <IconButton
              onClick={() => deleteInputedSkill(i)}
              icon={<TiDelete />}
              key={i}
              text={skillName}
            />
          ))}
          <div>
            <form onSubmit={handleOnSubmit}>
              <input
                className="outline-none border-b-2 border-b-green-500 text-lg text-green-700 bg-transparent"
                value={skillValue}
                placeholder="Enter your skill"
                onChange={(e) => setSkillValue(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Backspace") {
                    if (!skillValue) {
                      removeSkill();
                    }
                  }
                }}
                type="text"
              />
            </form>
          </div>
        </div>
        <p className="mb-2 font-medium"> Suggested Skills : </p>
        <div className="flex gap-2">
          {suggestedSkill.map(({ skillName }, i) => (
            <Skill
              onClick={(skill) => removeSuggestedSkill(skill)}
              skillName={skillName}
              key={i}
            />
          ))}
        </div>
      </div>
    </>
  );
};

export default Home;
